# 前言 {.unnumbered}

## 关于本书

This is a Quarto book. To learn more about Quarto books visit <https://quarto.org/docs/books>.

## 主要任务

`Markdown` 作为一种轻量级的标记语言，在日常的文档编辑中被广泛使用。然而，`Markdown` 的功能有些 “简陋”，并不能满足学术文档、技术文档的较复杂的排版需求。

`LaTeX` 作为一种专业的排版系统，在学术文档、技术文档的排版中被广泛使用。然而，`LaTeX` 的语法较为复杂，学习成本较高，对于初学者来说并不友好，即使熟练使用，也会花费大量的时间，效率不高。

`Quarto` 是 `Markdown` 的诸多扩展之一，在保持 `Markdown` 的简洁、易用的基础上，提供了丰富的功能以满足学术文档、技术文档的排版需求。本项目的工作就是把我们之前基于 LaTeX 的文档内容无缝地迁移到 Quarto 上来，从而实现**一份源代码，各种输出格式**的高效内容编辑工作流。

::: {.callout-note title="成果展示"}
最近在看 @cohen2022practical ，全当是对线性代数做一个偏应用的复习了。复习过程中所做的一些记录（当然是融合了以前的偏理论的内容）可以在 <https://strik0rium.github.io/linear-algebra-web/> 中查看。
:::

## 目标读者 & 前置知识储备

本书不适合在日常写作中不涉及大量公式、或更偏向于 `Markdown` 特性的读者，也不适合主要使用 `LaTeX` 且无需 `Markdown` 特性的用户，或者仅有 PDF 生成需求、没有 HTML 等格式输出和内容分发需求的人群，以及已经使用 Docusaurus 等其他基于 `Markdown` 的文档工具的读者。

本书适合已经具备一定 `Markdown` 和 `LaTeX` 基础，并且希望结合两者优势、提升写作效率的读者。需要使用 `LaTeX` 的读者，通常会在日常写作中涉及大量公式排版、`TikZ` 绘图，并希望通过各类 `LaTeX` 环境来对文档结构进行更灵活的划分。而对 `Markdown` 有需求的读者，则更希望凭借其简洁的语法，实现高效的图文混排、列表编辑^[这里的列表指的是无序列表和有序列表]、代码块编辑，并用 `callout` 特性生成醒目的提示信息等内容。

- 需要对`Markdown` 有一定的了解，熟悉`Markdown` 的语法，能够使用`Markdown` 编写文档。
- 需要读者完成 `LaTeX` 的环境配置，但这并不是必须的。没有完成 `LaTeX` 配置的读者可以参考 `Quarto` 的官方文档完成配置。如果你不确定你的 `LaTeX` 环境是否已经配置完成，可以尝试在系统终端中执行如下命令：
    
    ```zsh
    $ pdflatex --version
    $ xelatex --version
    $ lualatex --version
    $ latexmk --version
    ```
    如果上述命令都能正确输出版本信息，则说明你的 `LaTeX` 环境已经配置完成。否则，请参考 `Quarto` 的官方文档或者 [这个视频](https://www.bilibili.com/video/BV1xCNfejEMv) 完成配置。

## 致谢

感谢 @cohen2022practical 的作者，让我从此多了一个给偏 CS、DataSci、AI 和 FinTech 方向的同学推荐线性代数学习资料的选择，拒绝同济线性代数、北大高等代数等诸多防自学教材的理由又多了一个。

感谢 ChatGPT 和 Cursor，他们的编码能力实在是很强，帮我节省了许多工作量（但同时也让我多走了很多弯路）。

## 讲义获取

本系列没有 PDF 版讲义。