# Markdown 基础

Markdown 是一种轻量级的标记语言，用于将纯文本转换为格式化的文档。它最初由 John Gruber 和 Aaron Swartz 于 2004 年创建，旨在简化文本格式化过程。Markdown 的语法非常简单，易于学习和使用，因此被广泛应用于各种文档、博客、论坛和代码编辑器中。本章节主要介绍了 Markdown 的基础知识。

## 标题

Markdown 的标题使用 `#` 符号来表示，`#` 的数量表示标题的级别，`#` 越多，标题的级别越低。例如：

```markdown
# 一级标题
## 二级标题
### 三级标题
#### 四级标题
##### 五级标题
```

::: {.callout-warning}
标题级别不建议超过 4 级别，否则可能对 PDF 版本的 `LaTeX` 渲染产生影响。通常来说，一级标题表示 `chapter`，二级标题表示 `section`，三级标题表示 `subsection`，四级标题表示 `subsubsection`，照这样下去，五级标题就是 `paragraph`。

但是经过测试，渲染含有五级标题的 PDF 文档时会报错。
:::

## 段落

Markdown 的段落使用空行来表示，段落之间使用空行来分隔。

```markdown
这是一个段落，
代码中的换行会被解释为一个空格。

这是另一个段落，
同样，代码中的换行只能被认为是空格。
```

这是一个段落，
代码中的换行会被解释为一个空格。

这是另一个段落，
同样，代码中的换行只能被认为是空格。

## 列表

Quarto Markdown 支持多种列表类型，也支持混用不同样式的列表。

```markdown
- 无序列表项 1
- 无序列表项 2
- 无序列表项 3
```

- 无序列表项 1
- 无序列表项 2
- 无序列表项 3

```markdown
1. 有序列表项 1
2. 有序列表项 2
3. 有序列表项 3
```

1. 有序列表项 1
2. 有序列表项 2
3. 有序列表项 3

Quarto Markdown 也支持大写字母列表，这一列表使用大写拉丁字母作为标签，非常适合用于选择题的排版：

```markdown
A.  大写字母列表项 1
A.  大写字母列表项 2
A.  大写字母列表项 3
```

A.  大写字母列表项 1
A.  大写字母列表项 2
A.  大写字母列表项 3

::: {.callout-caution}
大写字母列表项的标签有两个空格。

```markdown
A. 只有一个空格
A.  有两个空格 <!-- 正确 -->
```

只打一个空格是不能触发 Quarto 的大写字母列表的：

```markdown
A. 只有一个空格
A. 只有一个空格
```

A. 只有一个空格
A. 只有一个空格

注意到上述代码的渲染结果是一个段落，而不是一个以大写字母为标签的列表。
:::

类似地，还可以将小写字母和复选框作为列表项的标签：

```markdown
a.  小写字母列表项  <!-- 两个空格 -->
- [ ] 复选框列表项
- [x] 复选框列表项（已勾选）
```

a.  小写字母列表项 <!-- 两个空格 -->
- [ ] 复选框列表项
- [x] 复选框列表项（已勾选）